# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number', models.CharField(max_length=15)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number', models.CharField(max_length=15)),
                ('car_model', models.CharField(blank=True, max_length=40)),
                ('car_reg_number', models.CharField(blank=True, max_length=10)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('tel_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('work_days', models.SmallIntegerField()),
                ('work_time_start', models.TimeField(blank=True)),
                ('work_time_end', models.TimeField(blank=True)),
                ('dinner_break_start', models.TimeField(blank=True)),
                ('dinner_break_end', models.TimeField(blank=True)),
                ('time_interval', models.TimeField(verbose_name=datetime.time(0, 15))),
                ('checkin_amount', models.SmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carwash.BusinessProfile')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carwash.ClientProfile'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carwash.Schedule'),
        ),
    ]
