# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_auto_20170731_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_interval',
            field=models.TimeField(default=datetime.time(0, 15)),
        ),
    ]
