# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_auto_20170807_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='dinner_break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dinner_break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
