# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0004_auto_20170808_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='active',
            field=models.SmallIntegerField(default=1),
        ),
    ]
